### ISSUE TITLE
Breaking changes in 0.7.0

### ISSUE THREAD

**Issue by jan-kantert** [puetzp/prometheus-http-query#8]
Updating to 0.7.0 broke quite a bit of code on our end. In my opinion this should only happen in major versions.

A few questions regarding migrating to 0.7.0:
- What is the new `Error::ResponseParse`. Is `Error::ParseUrl` the same thing?
- Client::metric_metadata lost its parameters. Is there a replacement or migration guide?

**Comment by puetzp** [comment]
According to semantic versioning the usual conventions regarding API changes do not apply during the "initial development" (version 0.y.z) phase. However I would certainly agree that at some point a 1.0.0 release should be cut instead of remaining forever in this "initial development" phase. This problem applies to a lot of Rust crates on crates.io.

Regarding your questions:

1. `Error::ResponseParse` is thrown when the JSON response from the Prometheus server cannot be parsed (is not as expected). `Error::ParseUrl` on the other hand is thrown when you create a `Client` and pass an invalid base URL. 
2. `Client::metric_metadata` lost its parameters but now returns a builder type. This type has methods that enable you to set the parameters that you would have passed to `Client::metric_metadata` directly in the 0.6.x versions of this crate. There is no migration guide as I had hoped that the documentation on docs.rs and the latest Changelog would suffice to explain the changes.

There are other `Client` methods that return builder types now (e.g. `Client::rules`. My reasoning for this is that the Prometheus HTTP API keeps evolving quite a bit and at some point the number of parameters that you add to a request becomes unwieldy. I think building a request to the API with a "builder" type is in some cases just better than having functions with a lot of optional parameters like `metric_metadata(None, None, None, None)`.

Let me know if there is anything else!

**Comment by jan-kantert** [comment]
Thanks for your fast reply and thanks for the library :-). 

We currently use `Error::Client` and `Error::ResponseParse` to catch any kind of connection reset/timeout or underlying network rrors and retry those (using the awesome `backoff` crate). Where would those errors end up now? I want to retry any transport errors.

**Comment by puetzp** [comment]
Actually I thought a bit about it and will add amongst others a `ClientError:inner()` method to get to the inner `reqwest::Error` without downcasting.
The downcasting is necessary because `Error::source()` returns `&(dyn Error)` and the `source()` method needs to be implemented for libraries like `anyhow` to work properly.
But there is no reason why we cannot make life easier by adding a "shortcut" to the inner error.
Then you could just do:

```rust
match client.metric_metadata().get().await {
    Ok(_) => println!("happy path"),
    Err(e) => match e {
        Error::Client(e) => if e.inner().is_timeout() {
            todo!();
        }
    }
}
```

Will be added in v0.7.1!

**Comment by puetzp** [comment]
Methods to retrieve underlying errors more quickly were added in v0.7.1. See for example [this](https://docs.rs/prometheus-http-query/latest/prometheus_http_query/error/struct.ClientError.html#method.inner).

I think this addresses your last question and will close this issue now!
